import { useState, useEffect } from 'react';
import {
  TrendingUp, Download, FileSpreadsheet,
  Users, Wallet, ArrowUpRight, ArrowDownRight, FileText,
  Loader2, AlertCircle
} from 'lucide-react';
import apiClient from '../services/api/client';

const fmt = (n) => {
  if (n == null) return '—';
  if (n >= 1_000_000) return `LKR ${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `LKR ${(n / 1_000).toFixed(1)}K`;
  return `LKR ${n.toLocaleString()}`;
};

const fmtRaw = (n) => (n == null ? '0' : n.toLocaleString());

// ── CSV / Excel helpers ──────────────────────────────────────────────────────
const downloadCSV = (rows, filename) => {
  const csv = rows.map(r => r.map(c => `"${String(c ?? '').replace(/"/g, '""')}"`).join(',')).join('\n');
  const blob = new Blob(['﻿' + csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
};

// ── PDF helpers ──────────────────────────────────────────────────────────────
const openPrintWindow = (html) => {
  const win = window.open('', '_blank');
  if (win) { win.document.write(html); win.document.close(); }
};

const pdfShell = (title, bodyHtml) => {
  const today = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' });
  const logoUrl = window.location.origin + '/logo.jpg';
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${title}</title>
  <style>
    *{margin:0;padding:0;box-sizing:border-box}
    body{font-family:Arial,sans-serif;font-size:13px;color:#1e293b;padding:40px}
    .header{display:flex;align-items:center;gap:20px;padding-bottom:20px;margin-bottom:24px;border-bottom:3px solid #10b981}
    .logo{width:64px;height:64px;object-fit:contain;border-radius:8px}
    .co h1{font-size:18px;font-weight:900;color:#0f172a;letter-spacing:1px}
    .co p{font-size:11px;color:#64748b;margin-top:3px}
    .meta{margin-left:auto;text-align:right;font-size:12px;color:#64748b}
    .meta strong{display:block;font-size:13px;color:#0f172a}
    h2{font-size:14px;font-weight:800;color:#0f172a;margin:24px 0 12px;border-left:4px solid #10b981;padding-left:10px}
    table{width:100%;border-collapse:collapse;margin-bottom:20px}
    th{background:#f1f5f9;text-align:left;padding:10px 14px;font-size:11px;font-weight:800;text-transform:uppercase;color:#94a3b8;border-bottom:1px solid #e2e8f0}
    td{padding:10px 14px;border-bottom:1px solid #f1f5f9;font-size:13px}
    .r{text-align:right} .c{text-align:center}
    .g{color:#059669;font-weight:800} .r2{color:#dc2626;font-weight:800} .b{color:#2563eb;font-weight:800} .p{color:#7c3aed;font-weight:800} .o{color:#d97706;font-weight:800}
    .kpi-row{display:flex;gap:12px;margin-bottom:20px;flex-wrap:wrap}
    .kpi{flex:1;min-width:140px;padding:12px 16px;border:1px solid #e2e8f0;border-radius:8px}
    .kpi label{font-size:10px;font-weight:800;text-transform:uppercase;color:#94a3b8}
    .kpi .val{font-size:17px;font-weight:900;color:#0f172a;margin-top:4px}
    .footer{margin-top:40px;padding-top:14px;border-top:1px solid #e2e8f0;font-size:11px;color:#94a3b8;text-align:center}
    @media print{body{padding:20px}}
  </style></head><body>
  <div class="header">
    <img class="logo" src="${logoUrl}" alt="NF Plantation"/>
    <div class="co"><h1>NF PLANTATION (PVT) LTD</h1><p>${title}</p></div>
    <div class="meta"><strong>Report Date</strong>${today}</div>
  </div>
  ${bodyHtml}
  <div class="footer">Auto-generated by NF Plantation Admin System. For internal use only. &copy; ${new Date().getFullYear()} NF Plantation (Pvt) Ltd.</div>
  <script>window.onload=function(){window.print()}</script>
  </body></html>`;
};

// ── Reports component ────────────────────────────────────────────────────────
const Reports = () => {
  const [activeTab, setActiveTab] = useState('finance');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [data, setData] = useState(null);

  useEffect(() => {
    const fetchSummary = async () => {
      try {
        setLoading(true);
        const res = await apiClient.get('/admin/reports/summary');
        if (res.success) setData(res.data);
        else setError('Failed to load report data.');
      } catch { setError('Could not connect to server.'); }
      finally { setLoading(false); }
    };
    fetchSummary();
  }, []);

  // ── Finance PDF ──────────────────────────────────────────────────────────
  const downloadFinancePDF = () => {
    if (!data?.finance) return;
    const f = data.finance;
    const rows = [
      ['Total Deposits (Approved)', fmt(f.totalDeposits), 'green'],
      ['Total Withdrawals (Processed)', fmt(f.totalWithdrawals), 'r2'],
      ['Active Capital Under Management', fmt(f.activeCapital), 'b'],
      ['Total Profit Paid to Customers', fmt(f.totalProfitPaid), 'p'],
      ['Pending Payouts (Queued)', fmt(f.pendingPayouts), 'o'],
    ];
    const body = `
      <h2>Financial Performance Summary</h2>
      <div class="kpi-row">
        <div class="kpi"><label>Active Capital</label><div class="val b">${fmt(f.activeCapital)}</div></div>
        <div class="kpi"><label>Total Deposits</label><div class="val g">${fmt(f.totalDeposits)}</div></div>
        <div class="kpi"><label>Total Withdrawals</label><div class="val r2">${fmt(f.totalWithdrawals)}</div></div>
        <div class="kpi"><label>Profit Paid</label><div class="val p">${fmt(f.totalProfitPaid)}</div></div>
        <div class="kpi"><label>Pending Payouts</label><div class="val o">${fmt(f.pendingPayouts)}</div></div>
      </div>
      <table><thead><tr><th>Metric</th><th class="r">Value</th></tr></thead><tbody>
        ${rows.map(([label, val, cls]) => `<tr><td>${label}</td><td class="r ${cls}">${val}</td></tr>`).join('')}
      </tbody></table>`;
    openPrintWindow(pdfShell('Financial Performance Report', body));
  };

  // ── Finance Excel ────────────────────────────────────────────────────────
  const downloadFinanceExcel = () => {
    if (!data?.finance) return;
    const f = data.finance;
    const rows = [
      ['Metric', 'Value (LKR)'],
      ['Total Deposits (Approved)', f.totalDeposits ?? 0],
      ['Total Withdrawals (Processed)', f.totalWithdrawals ?? 0],
      ['Active Capital Under Management', f.activeCapital ?? 0],
      ['Total Profit Paid to Customers', f.totalProfitPaid ?? 0],
      ['Pending Payouts (Queued)', f.pendingPayouts ?? 0],
    ];
    downloadCSV(rows, `NF_Finance_Report_${new Date().toISOString().slice(0,10)}.csv`);
  };

  // ── Customers PDF ────────────────────────────────────────────────────────
  const downloadCustomersPDF = () => {
    if (!data?.customers) return;
    const c = data.customers;
    const branchRows = (c.branchWise || []).map(b =>
      `<tr><td>${b.name}</td><td class="c">${b.total}</td><td class="c g">${b.active}</td><td class="c" style="color:#94a3b8">${b.inactive}</td></tr>`
    ).join('') || '<tr><td colspan="4" style="text-align:center;color:#94a3b8">No data</td></tr>';

    const body = `
      <h2>Customer Analytics</h2>
      <div class="kpi-row">
        <div class="kpi"><label>Total Customers</label><div class="val">${fmtRaw(c.totalCustomers)}</div></div>
        <div class="kpi"><label>KYC Verified</label><div class="val g">${fmtRaw(c.kycVerified)}</div></div>
        <div class="kpi"><label>KYC Completion</label><div class="val g">${c.kycRatio}%</div></div>
      </div>
      <h2>Branch-wise Distribution</h2>
      <table><thead><tr><th>Branch Name</th><th class="c">Total</th><th class="c">Active</th><th class="c">Inactive</th></tr></thead>
      <tbody>${branchRows}</tbody></table>`;
    openPrintWindow(pdfShell('Customer Analytics Report', body));
  };

  // ── Customers Excel ──────────────────────────────────────────────────────
  const downloadCustomersExcel = () => {
    if (!data?.customers) return;
    const c = data.customers;
    const rows = [
      ['Branch Name', 'Total Customers', 'Active', 'Inactive'],
      ...(c.branchWise || []).map(b => [b.name, b.total, b.active, b.inactive]),
      [],
      ['Summary', ''],
      ['Total Customers', c.totalCustomers],
      ['KYC Verified', c.kycVerified],
      ['KYC Completion %', c.kycRatio],
    ];
    downloadCSV(rows, `NF_Customer_Report_${new Date().toISOString().slice(0,10)}.csv`);
  };

  // ── Investment PDF ───────────────────────────────────────────────────────
  const downloadInvestmentsPDF = () => {
    if (!data?.investments) return;
    const planRows = (data.investments.planWise || []).map(p =>
      `<tr><td style="color:var(--primary)">${p.name}</td><td class="c">${p.active}</td><td class="c o">${p.matured}</td><td class="c" style="color:#64748b">${p.completed}</td><td class="r g">${fmt(p.totalAmount)}</td></tr>`
    ).join('') || '<tr><td colspan="5" style="text-align:center;color:#94a3b8">No data</td></tr>';

    const body = `
      <h2>Investment Portfolio – Plan-wise Maturity Report</h2>
      <table><thead><tr><th>Plan Level</th><th class="c">Active</th><th class="c">Matured</th><th class="c">Completed</th><th class="r">Portfolio Value</th></tr></thead>
      <tbody>${planRows}</tbody></table>`;
    openPrintWindow(pdfShell('Investment Portfolio Report', body));
  };

  // ── Investment Excel ─────────────────────────────────────────────────────
  const downloadInvestmentsExcel = () => {
    if (!data?.investments) return;
    const rows = [
      ['Plan Level', 'Active', 'Matured', 'Completed', 'Portfolio Value (LKR)'],
      ...(data.investments.planWise || []).map(p => [p.name, p.active, p.matured, p.completed, p.totalAmount ?? 0]),
    ];
    downloadCSV(rows, `NF_Investment_Report_${new Date().toISOString().slice(0,10)}.csv`);
  };

  const finance = data?.finance;
  const customers = data?.customers;
  const investments = data?.investments;

  const tabConfig = {
    finance: { label: 'Financial Performance', onPDF: downloadFinancePDF, onExcel: downloadFinanceExcel },
    customers: { label: 'Customer Analytics', onPDF: downloadCustomersPDF, onExcel: downloadCustomersExcel },
    investments: { label: 'Investment Portfolio', onPDF: downloadInvestmentsPDF, onExcel: downloadInvestmentsExcel },
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>

      {/* Module Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end' }}>
        <div>
          <h1 style={{ fontSize: '24px', fontWeight: '800', color: 'var(--text-main)', fontFamily: 'var(--font-display)' }}>Analytical Reports</h1>
          <p style={{ color: 'var(--text-muted)', fontSize: '14px', marginTop: '4px' }}>Comprehensive financial and operational performance intelligence for the plantation network.</p>
        </div>
        {data && (
          <div style={{ display: 'flex', gap: '10px' }}>
            <button
              className="btn-primary"
              onClick={tabConfig[activeTab].onPDF}
              style={{ display: 'flex', alignItems: 'center', gap: '8px' }}
            >
              <Download size={16} /> Download PDF
            </button>
            <button
              onClick={tabConfig[activeTab].onExcel}
              style={{
                display: 'flex', alignItems: 'center', gap: '8px',
                padding: '10px 18px', borderRadius: '10px', fontWeight: '800', fontSize: '14px',
                backgroundColor: '#f0fdf4', color: '#166534', border: '1px solid #bbf7d0',
                cursor: 'pointer'
              }}
            >
              <FileSpreadsheet size={16} /> Download Excel
            </button>
          </div>
        )}
      </div>

      {/* Tabs */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '0', borderBottom: '2px solid #f1f5f9' }}>
        {Object.entries(tabConfig).map(([key, cfg]) => (
          <button
            key={key}
            onClick={() => setActiveTab(key)}
            style={{
              padding: '12px 24px', fontSize: '14px', fontWeight: '800',
              color: activeTab === key ? 'var(--primary)' : '#64748b',
              borderBottom: activeTab === key ? '2px solid var(--primary)' : '2px solid transparent',
              marginBottom: '-2px',
              transition: 'all 0.2s',
              background: 'none'
            }}
          >
            {cfg.label}
          </button>
        ))}
      </div>

      {loading && (
        <div style={{ textAlign: 'center', padding: '80px' }}>
          <Loader2 size={32} className="animate-spin" style={{ color: 'var(--primary)', margin: '0 auto 12px' }} />
          <p style={{ color: '#94a3b8', fontWeight: '600' }}>Loading report data...</p>
        </div>
      )}

      {error && !loading && (
        <div className="card" style={{ padding: '24px', backgroundColor: '#fef2f2', border: '1px solid #fecaca', display: 'flex', alignItems: 'center', gap: '12px', color: '#dc2626' }}>
          <AlertCircle size={20} /> {error}
        </div>
      )}

      {!loading && !error && data && (
        <>
          {/* ── FINANCIAL PERFORMANCE ── */}
          {activeTab === 'finance' && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: '16px' }}>
                {[
                  { label: 'Total Deposits', value: fmt(finance?.totalDeposits), icon: <ArrowDownRight />, color: '#10b981' },
                  { label: 'Total Withdrawals', value: fmt(finance?.totalWithdrawals), icon: <ArrowUpRight />, color: '#ef4444' },
                  { label: 'Active Capital', value: fmt(finance?.activeCapital), icon: <Wallet />, color: 'var(--primary)' },
                  { label: 'Profit Paid', value: fmt(finance?.totalProfitPaid), icon: <TrendingUp />, color: '#8b5cf6' },
                  { label: 'Pending Payouts', value: fmt(finance?.pendingPayouts), icon: <FileText />, color: '#f59e0b' },
                ].map((item, i) => (
                  <div key={i} className="card" style={{ display: 'flex', flexWrap: 'wrap', gap: '12px' }}>
                    <div style={{ width: '40px', height: '40px', borderRadius: '10px', backgroundColor: `${item.color}15`, color: item.color, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      {item.icon}
                    </div>
                    <div>
                      <p style={{ fontSize: '11px', fontWeight: '800', color: '#94a3b8', textTransform: 'uppercase' }}>{item.label}</p>
                      <p style={{ fontSize: '15px', fontWeight: '800', color: 'var(--text-main)' }}>{item.value}</p>
                    </div>
                  </div>
                ))}
              </div>

              <div className="card">
                <h3 style={{ fontSize: '16px', fontWeight: '800', marginBottom: '12px' }}>Finance Overview</h3>
                <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                  <thead style={{ backgroundColor: '#f8fafc' }}>
                    <tr>
                      <th style={{ textAlign: 'left', padding: '14px 20px', fontSize: '11px', fontWeight: '800', color: '#94a3b8' }}>METRIC</th>
                      <th style={{ textAlign: 'right', padding: '14px 20px', fontSize: '11px', fontWeight: '800', color: '#94a3b8' }}>VALUE</th>
                    </tr>
                  </thead>
                  <tbody>
                    {[
                      { label: 'Total Deposits (Approved)', value: fmt(finance?.totalDeposits), color: '#059669' },
                      { label: 'Total Withdrawals (Processed)', value: fmt(finance?.totalWithdrawals), color: '#dc2626' },
                      { label: 'Active Capital Under Management', value: fmt(finance?.activeCapital), color: '#2563eb' },
                      { label: 'Total Profit Paid to Customers', value: fmt(finance?.totalProfitPaid), color: '#7c3aed' },
                      { label: 'Pending Payouts (Queued)', value: fmt(finance?.pendingPayouts), color: '#d97706' },
                    ].map((row, i) => (
                      <tr key={i} style={{ borderBottom: '1px solid #f1f5f9' }}>
                        <td style={{ padding: '14px 20px', fontSize: '14px', fontWeight: '600' }}>{row.label}</td>
                        <td style={{ padding: '14px 20px', textAlign: 'right', fontSize: '15px', fontWeight: '800', color: row.color }}>{row.value}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* ── CUSTOMER ANALYTICS ── */}
          {activeTab === 'customers' && (
            <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1.5fr) 1fr', gap: '24px' }}>
              <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
                <div style={{ padding: '20px 24px', borderBottom: '1px solid #f1f5f9' }}>
                  <h3 style={{ fontSize: '16px', fontWeight: '800' }}>Branch-wise Customer Distribution</h3>
                </div>
                <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                  <thead style={{ backgroundColor: '#f8fafc' }}>
                    <tr>
                      <th style={{ textAlign: 'left', padding: '16px 24px', fontSize: '11px', fontWeight: '800', color: '#94a3b8' }}>BRANCH NAME</th>
                      <th style={{ textAlign: 'center', padding: '16px', fontSize: '11px', fontWeight: '800', color: '#94a3b8' }}>TOTAL</th>
                      <th style={{ textAlign: 'center', padding: '16px', fontSize: '11px', fontWeight: '800', color: '#94a3b8' }}>ACTIVE</th>
                      <th style={{ textAlign: 'center', padding: '16px', fontSize: '11px', fontWeight: '800', color: '#94a3b8' }}>INACTIVE</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(customers?.branchWise || []).length === 0 ? (
                      <tr><td colSpan={4} style={{ padding: '32px', textAlign: 'center', color: '#94a3b8' }}>No branch data available</td></tr>
                    ) : (customers?.branchWise || []).map((br, i) => (
                      <tr key={i} style={{ borderBottom: '1px solid #f1f5f9' }}>
                        <td style={{ padding: '16px 24px', fontSize: '14px', fontWeight: '700' }}>{br.name}</td>
                        <td style={{ padding: '16px', textAlign: 'center', fontSize: '14px', fontWeight: '800', color: '#1e293b' }}>{br.total}</td>
                        <td style={{ padding: '16px', textAlign: 'center', fontSize: '14px', fontWeight: '800', color: '#059669' }}>{br.active}</td>
                        <td style={{ padding: '16px', textAlign: 'center', fontSize: '14px', fontWeight: '800', color: '#94a3b8' }}>{br.inactive}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <div className="card">
                <h3 style={{ fontSize: '16px', fontWeight: '800', marginBottom: '20px' }}>KYC Completion Ratio</h3>
                <div style={{ height: '220px', backgroundColor: '#f8fafc', borderRadius: '12px', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '12px' }}>
                  <div style={{ width: '100px', height: '100px', borderRadius: '50%', background: `conic-gradient(#10b981 ${customers?.kycRatio || 0}%, #e2e8f0 0)`, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <div style={{ width: '70px', height: '70px', borderRadius: '50%', backgroundColor: '#f8fafc', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      <span style={{ fontSize: '15px', fontWeight: '900', color: '#10b981' }}>{customers?.kycRatio}%</span>
                    </div>
                  </div>
                  <p style={{ fontSize: '13px', fontWeight: '700', color: '#64748b' }}>Verified Customers</p>
                  <p style={{ fontSize: '12px', color: '#94a3b8' }}>{customers?.kycVerified?.toLocaleString()} of {customers?.totalCustomers?.toLocaleString()} total</p>
                </div>

                <div style={{ marginTop: '20px', display: 'flex', flexDirection: 'column', gap: '12px' }}>
                  {[
                    { label: 'Total Registered', value: fmtRaw(customers?.totalCustomers), color: '#1e293b' },
                    { label: 'KYC Verified', value: fmtRaw(customers?.kycVerified), color: '#059669' },
                    { label: 'Pending KYC', value: fmtRaw((customers?.totalCustomers || 0) - (customers?.kycVerified || 0)), color: '#f59e0b' },
                  ].map((r, i) => (
                    <div key={i} style={{ display: 'flex', justifyContent: 'space-between', padding: '10px 14px', borderRadius: '8px', backgroundColor: '#f8fafc' }}>
                      <span style={{ fontSize: '13px', fontWeight: '700', color: '#64748b' }}>{r.label}</span>
                      <span style={{ fontSize: '14px', fontWeight: '800', color: r.color }}>{r.value}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* ── INVESTMENT PORTFOLIO ── */}
          {activeTab === 'investments' && (
            <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
              <div style={{ padding: '20px 24px', borderBottom: '1px solid #f1f5f9' }}>
                <h3 style={{ fontSize: '16px', fontWeight: '800' }}>Plan-wise Investment Maturity Report</h3>
              </div>
              <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                <thead style={{ backgroundColor: '#f8fafc' }}>
                  <tr>
                    <th style={{ textAlign: 'left', padding: '16px 24px', fontSize: '11px', fontWeight: '800', color: '#94a3b8' }}>PLAN LEVEL</th>
                    <th style={{ textAlign: 'center', padding: '16px', fontSize: '11px', fontWeight: '800', color: '#94a3b8' }}>ACTIVE</th>
                    <th style={{ textAlign: 'center', padding: '16px', fontSize: '11px', fontWeight: '800', color: '#94a3b8' }}>MATURED</th>
                    <th style={{ textAlign: 'center', padding: '16px', fontSize: '11px', fontWeight: '800', color: '#94a3b8' }}>COMPLETED</th>
                    <th style={{ textAlign: 'right', padding: '16px 24px', fontSize: '11px', fontWeight: '800', color: '#94a3b8' }}>PORTFOLIO VALUE</th>
                  </tr>
                </thead>
                <tbody>
                  {(investments?.planWise || []).length === 0 ? (
                    <tr><td colSpan={5} style={{ padding: '32px', textAlign: 'center', color: '#94a3b8' }}>No investment data available</td></tr>
                  ) : (investments?.planWise || []).map((plan, i) => (
                    <tr key={i} style={{ borderBottom: '1px solid #f1f5f9' }}>
                      <td style={{ padding: '16px 24px', fontSize: '14px', fontWeight: '700', color: 'var(--primary)' }}>{plan.name}</td>
                      <td style={{ padding: '16px', textAlign: 'center', fontSize: '14px', fontWeight: '800' }}>{plan.active}</td>
                      <td style={{ padding: '16px', textAlign: 'center', fontSize: '14px', fontWeight: '800', color: '#f59e0b' }}>{plan.matured}</td>
                      <td style={{ padding: '16px', textAlign: 'center', fontSize: '14px', fontWeight: '800', color: '#64748b' }}>{plan.completed}</td>
                      <td style={{ padding: '16px 24px', textAlign: 'right', fontSize: '14px', fontWeight: '800', color: '#166534' }}>{fmt(plan.totalAmount)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </>
      )}
    </div>
  );
};

export default Reports;
