module.exports = {
    ROLES: {
        ADMIN: 'ADMIN',
        CUSTOMER: 'CUSTOMER',
        STAFF: 'STAFF'
    },
    WORKFLOW_STATUS: {
        PENDING: 'PENDING',
        UNDER_REVIEW: 'UNDER_REVIEW',
        APPROVED: 'APPROVED',
        REJECTED: 'REJECTED',
        RESUBMISSION_REQUIRED: 'RESUBMISSION_REQUIRED'
    },
    TRANSACTION_TYPES: {
        DEPOSIT_APPROVED: 'DEPOSIT_APPROVED',
        WITHDRAWAL_COMPLETED: 'WITHDRAWAL_COMPLETED',
        EARNING: 'EARNING',
        HOLD: 'HOLD',
        RELEASE: 'RELEASE',
        ADJUSTMENT: 'ADJUSTMENT'
    },
    APPLICATION_STATUS: {
        DRAFT: 'DRAFT',
        SUBMITTED: 'SUBMITTED',
        UNDER_REVIEW: 'UNDER_REVIEW',
        REJECTED: 'REJECTED',
        APPROVED: 'APPROVED'
    }
};
